### ISSUE TITLE
hpp-template-corba dependency

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-affordance-corba#7]
Hi,

According to https://github.com/humanoid-path-planner/hpp-affordance-corba/blob/master/CMakeLists.txt#L43, this package depends on hpp-template-corba.

But if I understood @florent-lamiraux correctly, hpp-template-corba should just be used to be copy-pasted in order to create a new repo, right ?

**Comment by florent-lamiraux** [comment]
Not at all. The word "template" might be misleading, but it is a real package that provides a C++ template class the argument of which is a class produced by the CORBA compiler from an idl file.

**Comment by nim65s** [comment]
Ok, thanks for the clarification :)
